//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goRatio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        public Bar()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public int MaleCount { get; set; }
        public int FemaleCount { get; set; }
        public string Vicinity { get; set; }
        public string PlaceId { get; set; }
        public string Rating { get; set; }
        public string Reference { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
