//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goRatio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public string DeviceToken { get; set; }
        public string Gender { get; set; }
        public string DeviceType { get; set; }
        public bool deviceForeground { get; set; }
        public bool AllowPush { get; set; }
        public string DUID { get; set; }
        public System.DateTime LastUpdatedLocation { get; set; }
    
        public virtual Bar Bar { get; set; }
    }
}
